/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Fri Nov 04 2016 16:06:21 GMT-0500 (CDT).
 */

define(['css!./styles/MLSimulatorWidget.css'], function () {
    'use strict';

    var MLSimulatorWidget,
        WIDGET_CLASS = 'm-l-simulator';

    MLSimulatorWidget = function (logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    };

    MLSimulatorWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header 
        this._el.append('<h3>MLSimulator Events:</h3>');

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });

        //Notebook
        var notebookIframe = document.createElement('iframe');
        notebookIframe.name = "notebook";
        notebookIframe.style.height = "100%";
        notebookIframe.style.width = "100%";
        notebookIframe.src = "ipython";
        notebookIframe.src = this.getNotebookUrl();
        this._el.append(notebookIframe);

        this.notebookIframe = notebookIframe;
    };

    MLSimulatorWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    MLSimulatorWidget.prototype.getNotebookUrl = function (desc) {
        // Replace "localhost:9999" with "moca.isis.vanderbilt.edu" if you're running this on localhost
        return "http://localhost:8888/notebooks/dataAnalytics/notebooks/abc.ipynb";
        //return "ipython/notebooks/" + WebGMEGlobal.userInfo._id + "/"
        //    + desc.projectName + "/"
        //    + desc.name + ".ipynb";
    };



    // Adding/Removing/Updating items
    MLSimulatorWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' + 
                desc.childrenIds.length + ' ' + label + '.';

            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    MLSimulatorWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    MLSimulatorWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    MLSimulatorWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    MLSimulatorWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    MLSimulatorWidget.prototype.destroy = function () {
    };

    MLSimulatorWidget.prototype.onActivate = function () {
        this._logger.debug('MLSimulatorWidget has been activated');
    };

    MLSimulatorWidget.prototype.onDeactivate = function () {
        this._logger.debug('MLSimulatorWidget has been deactivated');
    };

    return MLSimulatorWidget;
});
